In [2]:
import torch

##### Initializing a tensor

In [3]:
ten1 = torch.tensor([[1,2,3],[4,5,6]])
print(ten1)

ten2 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(ten2)

print(ten2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


#####  Other initialization methods

In [4]:
x = torch.empty(size=(3,3))
print(x)

y = torch.zeros((3,3))
print(y)

z = torch.ones((3,3))
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
r = torch.rand((3,3))
print(r)

identity = torch.eye(3,3)
print(identity)

#here we define the steps size and the size of tensor is decided by: range/stepsize
arrange = torch.arange(start=0, end=10, step=1)
print(arrange)
tensor = torch.arange(4)
print(tensor)

#here we decide the size of tensor, hence stepsize is calc as: range/size
lin = torch.linspace(start=0.1, end = 1, steps=10)
print(lin)

tensor([[0.0530, 0.8459, 0.4538],
        [0.9268, 0.2584, 0.0057],
        [0.4950, 0.5973, 0.0700]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [10]:
# Normally distributed with mean=0, std=1
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1) 
print(x) 

# Values from a uniform distribution low=0, high=1
x = torch.empty(size=(1, 5)).uniform_(0, 1)  
print(x)

x = torch.diag(torch.ones(3))
print(x)

tensor([[-1.5607, -0.9606, -0.5420,  0.0918,  1.0588]])
tensor([[0.1592, 0.2104, 0.3348, 0.3092, 0.7132]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


##### Conversion

In [16]:
print(f"Original tensor: {tensor}")

# Converted to Boolean: 1 if nonzero
print(f"\nConverted Boolean: {tensor.bool()}") 

# Converted to int16
print(f"\nConverted int16 {tensor.short()}")  

# Converted to int64 (This one is very important, used super often)
print(f"\nConverted int64 {tensor.long()}")  

# Converted to float16
print(f"\nConverted float16 {tensor.half()}")  

# Converted to float32 (This one is very important, used super often)
print(f"\nConverted float32 {tensor.float()}")  

# Converted to float64
print(f"\nConverted float64 {tensor.double()}")  

Original tensor: tensor([0, 1, 2, 3])

Converted Boolean: tensor([False,  True,  True,  True])

Converted int16 tensor([0, 1, 2, 3], dtype=torch.int16)

Converted int64 tensor([0, 1, 2, 3])

Converted float16 tensor([0., 1., 2., 3.], dtype=torch.float16)

Converted float32 tensor([0., 1., 2., 3.])

Converted float64 tensor([0., 1., 2., 3.], dtype=torch.float64)


##### Array to Tensor to Array

In [18]:
import numpy as np

np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
print(tensor)

# np_array_again will be same as np_array (perhaps with numerical round offs)
np_array_again = (tensor.numpy())  
print(np_array_again)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##### Tensor Math

In [21]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# -- Addition --

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([10, 10, 10])


Addition

In [26]:
z1 = torch.empty(3)

# This is one way
torch.add(x, y, out=z1)  

# This is second way
z2 = torch.add(x,y)

# This is another way
z3 = torch.add(x, y) 

# This is my preferred way, simple and clean.
z = x + y  

print(z1)
print(z2)
print(z3)
print(z)

#in place addn: t += x
t = torch.zeros(3)
t.add_(x)
print(t)

t+=x
print(t)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([1., 2., 3.])
tensor([2., 4., 6.])


Subtraction

In [22]:
z = x - y 
print(z)

z = torch.sub(x,y)
print(z)

torch.sub(x,y, out=z)
print(z)

tensor([-8, -6, -4])
tensor([-8, -6, -4])
tensor([-8, -6, -4])


Multiplication

In [23]:
z = x*y
print(z)

z = torch.mul(x,y)
print(z)

torch.mul(x,y, out=z)
print(z)

tensor([ 9, 16, 21])
tensor([ 9, 16, 21])
tensor([ 9, 16, 21])


Division

In [24]:
z = torch.true_divide(x, y)  
print(z)

# Will do element wise division if of equal shape
z = x/y
print(z)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.1111, 0.2500, 0.4286])


Slicing

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1